[build]
  # Since we're using vanilla HTML/CSS/JS, no build process needed
  publish = "."
  
[build.environment]
  # No environment variables needed for this static site

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  # Cache static assets
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (optional)
[[redirects]]
  from = "/canvas"
  to = "/"
  status = 301

[[redirects]]
  from = "/draw"
  to = "/"
  status = 301
